"""Backend module selector.

Dev mode: backend name picked from env var (``PLYUNIT_BACKEND``).
Build mode (Nuitka): ``_build_lock.py`` is generated by the build script
with the frozen backend name; Nuitka can statically trace the if/elif chain
below because every branch resolves to a literal import.

Integration, physics, and ImGui selection is consumed by their lazy
facades (``__getattr__`` dispatch).
"""

from __future__ import annotations

try:
    # For build only
    # pyrefly: ignore [missing-import]
    from ._build_lock import BACKEND, NATIVE_BUILD, PHYSICS_BACKEND
except ImportError:
    from .._config import BACKEND, NATIVE_BUILD, PHYSICS_BACKEND

from . import _registry


def _integration(name: str) -> str:
    """Select the module path for the given integration backend name.

    Args:
        name: Integration backend name.

    Returns:
        The corresponding Python module path (string).

    Raises:
        ValueError: If ``name`` is not in the registry.
    """
    if name not in _registry.INTEGRATION_BACKENDS:
        raise ValueError(
            f"Unknown integration backend {name!r}; "
            f"known: {_registry.INTEGRATION_BACKENDS}"
        )
    # Static chain — Nuitka must see every branch resolve to a literal.
    if name == "raylib":
        return "plyunit.backends.integrations.raylib"
    raise ValueError(f"No module for integration backend {name!r}")


def _physics(name: str) -> str:
    """Select the module path for the given physics backend name.

    Args:
        name: Physics backend name.

    Returns:
        The corresponding Python module path (string).

    Raises:
        ValueError: If ``name`` is not in the registry.
    """
    if name not in _registry.PHYSICS_BACKENDS:
        raise ValueError(
            f"Unknown physics backend {name!r}; known: {_registry.PHYSICS_BACKENDS}"
        )
    if name == "pymunk":
        return "plyunit.backends.physics.pymunk"
    raise ValueError(f"No module for physics backend {name!r}")


def integration_module() -> str:
    """Return the module path of the currently active integration backend."""
    return _integration(BACKEND)


def physics_module() -> str:
    """Return the module path of the currently active physics backend."""
    return _physics(PHYSICS_BACKEND)


def imgui_module() -> str:
    """Return the ImGui backend module path (follows the integration backend)."""
    # ImGui and integration share the same host (e.g. raylib).
    integ = integration_module()
    # "plyunit.backends.integrations.raylib" -> "plyunit.backends.imgui.raylib"
    head, _, tail = integ.rpartition("integrations.")
    return f"{head}imgui.{tail}"


__all__ = [
    "BACKEND",
    "NATIVE_BUILD",
    "PHYSICS_BACKEND",
    "imgui_module",
    "integration_module",
    "physics_module",
]
