"""plyunit package version (generated by hatchling)."""

#: SemVer version string of the package, read by ``plyunit.__init__`` and
#: exposed as ``plyunit.__version__``. Automatically overwritten by hatchling
#: when building a wheel/sdist.
__version__ = "0.1.0"
